### ISSUE TITLE
there is an error when i run this code in my own projects but i don`t know why 

### ISSUE THREAD

**Issue by 1579109909** [takashiishida/flooding#3]
images, labels = data
        labels = labels.to(device)
        outputs = net(images.to(device))
        loss = loss_function(outputs, labels)
        loss = (loss-b).abs() + b
        optimizer.zero_grad()
        writer.add_scalar('flood', loss, epoch + 1)
        loss.backward()
        optimizer.step()
TypeError: unsupported operand type(s) for -: 'Tensor' and 'str'

here are parts of my project  please help me check 
Thanks!!!!

**Comment by takashiishida** [comment]
Hi, do you know which part of the code is causing this error? Is it line 5? It looks like an TypeError, so can you also check the types?

**Comment by 1579109909** [comment]
thanks! i change the code here and it worked :
 images, labels = data
        labels = labels.to(device)
        outputs = net(images.to(device))
        loss = loss_function(outputs, labels)
        # loss = (loss-b).abs()+b
        loss=(loss-torch.tensor(0.02).to(device)).abs()+torch.tensor(0.02).to(device)
        optimizer.zero_grad()
        # writer.add_scalar('train_lo', loss, epoch + 1)
        loss.backward()
        optimizer.step()


i think it is a python frame problem 
it is like when python define a torch.tensor() outside a loop,
when pytorch run a epoch , the tensor would not be calculated 
anyway，  thanks to your work here for training strategy！！！！

good job!!!
and be happy

**Comment by takashiishida** [comment]
Thanks!
